// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package html2image4j;

@net.sf.jni4net.attributes.ClrType
public class ConvertHtmlToImage extends system.Object implements IHtml2Image {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ConvertHtmlToImage(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public ConvertHtmlToImage() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        ConvertHtmlToImage.__ctorConvertHtmlToImage0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorConvertHtmlToImage0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;ILSystem/String;)LSystem/String;")
    public native String ConvertHtmlToImage(String url, int width_px, String imageFile);
    
    public static system.Type typeof() {
        return ConvertHtmlToImage.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        ConvertHtmlToImage.staticType = staticType;
    }
    //</generated-proxy>
}
