// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package html2image4j;

@net.sf.jni4net.attributes.ClrInterface
public interface IHtml2Image {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;ILSystem/String;)LSystem/String;")
    String ConvertHtmlToImage(String url, int width_px, String imageFile);
    //</generated-interface>
}
