server:
  port: 8761
eureka:
  instance:
    hostname: 10.48.5.33
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
